name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main # chỉ chạy khi push vào branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull source code
        uses: actions/checkout@v3

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-26-97-252.ap-southeast-2.compute.amazonaws.com << 'EOF'
            cd ~/Twitter_API
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up --build -d
          EOF
