name: CI/CD Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js (nếu cần build trước, không bắt buộc)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: SCP files to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: '.'
          target: '/home/ubuntu/Twitter_API'

      - name: SSH and restart Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Twitter_API

            # 1) Dừng & xóa sạch container + volumes (Compose V2 hoặc fallback V1)
            if command -v docker compose > /dev/null; then
              docker compose down --remove-orphans --volumes
            else
              docker-compose down --remove-orphans --volumes
            fi

            # 2) Build & recreate container hoàn toàn
            if command -v docker compose > /dev/null; then
              docker compose up -d --build --force-recreate --remove-orphans
            else
              docker-compose up -d --build --force-recreate --remove-orphans
            fi
